defaults :
  - physicsnemo_default
  - optimizer : adam
  - scheduler : tf_exponential_lr
  - loss : sum
  - _self_

jit: false

optimizer:
  lr: 1e-3

scheduler:
  decay_rate: 0.95
  decay_steps: 8000

training: 
  rec_validation_freq: 1000
  rec_inference_freq: 1000
  rec_monitor_freq: 1000
  rec_constraint_freq: 1000
  max_steps: 300000

batch_size:
  interior: 2000
  boundary: 1000
  heat_source: 1000

custom:
  network: modified_fourier_net
  layer_size: 512
  activation: silu
