defaults:
- physicsnemo_default
-   scheduler: tf_exponential_lr
-   optimizer: adam
-   loss: sum
- _self_

optimizer:
  lr: 1e-3

custom:
    activation: silu
    parametric: false
    layer_size: 256
    num_layers: 5
scheduler:
    decay_rate: 0.95
    decay_steps: 5000
training:
    max_steps: 200000
batch_size:
    wall: 100
    interior: 1000
